### PR TITLE
Add trajectory selection

### PR DESCRIPTION
**Pull request by ofirlang**

### CODE REVIEW

**Comment by guy-av** [comment]
Didn't @royayal1 and Adi decided no trajectory is needed?

**Comment by GlebiN** [comment]
> Didn't @royayal1 and Adi decided no trajectory is needed?

They said there is no need in complex trajectory(path weaver/planner), but there's still would be at least 2.

**Comment by royayal1** [comment]
> > Didn't @royayal1 and Adi decided no trajectory is needed?
> 
> 
> 
> They said there is no need in complex trajectory(path weaver/planner), but there's still would be at least 2.


Actually it's exactly two, @guy-av   They're what i sent on the whatsapp gc

**Review by royayal1 — APPROVED** [review]
seems legit

**Pull request merged**
